### ISSUE TITLE
Problems with Python3.8 

### ISSUE THREAD

**Issue by mikelitu** [ScheiklP/sofa_env#14]
Hi @ScheiklP,

I have been trying the repository in the last few days, and I saw that you have update the minimum required python version to *3.8*. Even though the tests pass using this verion and the simple scene *controllable_object_example* would work, people will experience problems in other scenes. For example, if you try running environment *deflect_spheres*, an error will raise regarding the impossibility of performing the **bitwise OR (|) operator** between defaultdict and dict. This is coming from line 290 on **deflect_spheres_env.py**.

```python3
self.reward_amount_dict = defaultdict(float) | reward_amount_dict
```
This was solved in *Python3.9* on [PEP 584](https://peps.python.org/pep-0584/). Not sure if you were aware about this, but it may lead to some confusion for future users. Maybe it will be a good idea to talk with the people from SOFA so they update the binaries with a newer version of Python to solve this issue and have full compatibility with this repository. Another solution would be to create a **Docker Image** to self contain the requirements to run this repository from any computer. I hope his comment helps.

Best,
Mikel

**Comment by ScheiklP** [comment]
Hi Mikel,
good catch, thanks!

Compatibility with the SOFA binaries was actually never a main goal, since I also frequently contributed to SofaPython3 and preferred to build SOFA from source.
The `setup.py` already requires at least python 3.9.

I already talked to the SOFA guys, that a more modern python version would be great. :)

Cheers,
Paul
